version: 1.2.3
services:
  - name: a-microservice
    version: 1.2.4
  - name: just-another-microservice
    version: 1.2.5
  - name: default-microservice
  - name: this-one-also-uses-top-level-version
  - name: not-default-microservice
    version: 1.2.6